# Generated by Django 4.2.5 on 2023-09-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='company')),
                ('main_subtitle', models.TextField(blank=True, max_length=500, null=True)),
                ('about_subtitle', models.TextField(blank=True, max_length=500, null=True)),
                ('quran_subtitle', models.TextField(blank=True, max_length=500, null=True)),
                ('prayer_subtitle', models.TextField(blank=True, max_length=500, null=True)),
                ('awareness_subtitle', models.TextField(blank=True, max_length=500, null=True)),
                ('ramdan_subtitle', models.TextField(blank=True, max_length=500, null=True)),
                ('charity_and_donation_subtitle', models.TextField(blank=True, max_length=500, null=True)),
                ('haij_subtitle', models.TextField(blank=True, max_length=500, null=True)),
                ('shahadah_subtitle', models.TextField(blank=True, max_length=500, null=True)),
                ('fasting_subtitle', models.TextField(blank=True, max_length=500, null=True)),
                ('zakat_subtitle', models.TextField(blank=True, max_length=500, null=True)),
                ('facbook_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('instgram_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('phones', models.TextField(blank=True, max_length=500, null=True)),
                ('email', models.TextField(blank=True, max_length=500, null=True)),
                ('address', models.TextField(blank=True, max_length=500, null=True)),
                ('android_app', models.URLField(blank=True, null=True)),
                ('ios_app', models.URLField(blank=True, null=True)),
                ('call_us', models.CharField(blank=True, max_length=100, null=True)),
                ('email_us', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
